@BASE = http://127.0.0.1:8080/api/v1

#REQUESTS
GET {{BASE}}/degrees

###

GET {{BASE}}/degrees/2

###

DELETE {{BASE}}/degrees/2

###

POST {{BASE}}/register
Content-Type: application/json

{
    "accessMethod": "Selectividad",
    "dni": "67676767C",
    "firstName": "Nape",
    "surname": "Riggas Alltime",
    "birthDate": "1967-10-14",
    "email": "naprigall@alum.us.es",
    "password": "TeVoyADarCorrienteComoPikachu"
}

###
# @name login
POST {{BASE}}/login
Content-Type: application/json

{
    "email": "naprigall@alum.us.es",
    "password": "TeVoyADarCorrienteComoPikachu"
}

###

POST {{BASE}}/degrees
Content-Type: application/json
Token: {{login.response.body.sessionToken}}

{
    "name": "Ingeniería de Sistemas",
    "years": 4
}

###

PUT {{BASE}}/degrees/4
Content-Type: application/json
Token: {{login.response.body.sessionToken}}

{
    "name": "Ingeniería de la Salud",
    "years": 4
}

###

GET {{BASE}}/degrees/2/subjects

